#!/bin/bash
curl -O https://bulkdata.uspto.gov/data2/patent/application/redbook/fulltext/2017/"$1"
unzip "$1"
f=$(echo $1 | cut -f 1 -d '.') #removes extension
if [ ! -d "$f" ]; then
  mkdir "$f"
fi

Rscript xml2csv2.R "$1"

cd "$f"
ls | xargs cat > "$f.csv"
cat ../colnames "$f.csv" > "$f.csv"
cd ~